config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'registrations/sign_up_params'
  devise_for :users
  root :to => "homes#top"
  get "/about" => "homes#about"

  # ゲストログイン機能
  get '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search/search'
  get '/search', to: 'searches#search'

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get 'confirm' => 'users#confirm'
      patch 'hide' => 'users#hide'
      put "/users/:id/hide" => "users#hide", as: 'users_hide'
    end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
  validates :content, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    # 検索時
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.user_id = current_user.id
    unless @post_comment.save!
      render 'error'
    end
  end

  def destroy
    # コメントをfindしてdestroyを呼び出す
    # 削除したいコメントを呼び出す
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:content)
  end
end

app/views/post_comments/_index.html.erb
  <% post.post_comments.each do |post_comment| %>
    <% post_comment_user = post_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
      		<%= attachment_image_tag post_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50", class:"mt-3 rounded-circle"; %><br>
      		<%= post_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= post_comment.content %></td>
        <% if user_signed_in? && post_comment.user_id == current_user.id %>
          <td><%= link_to '削除', post_post_comment_path(post_comment.post_id, post_comment.id), method: :delete, class: "btn btn-danger comment-btn" ,data: { confirm: "削除してもいいですか？" }, remote: true %></td>
        <% end %>
    </tr>
  <% end %>

app/views/post_comments/create.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$("#post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_content").val("");

app/views/post_comments/destroy.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$("#post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_content").val("");