config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'registrations/sign_up_params'
  devise_for :users
  root :to => "homes#top"
  get "/about" => "homes#about"

  # ゲストログイン機能
  get '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search/search'
  get '/search', to: 'searches#search'

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get 'confirm' => 'users#confirm'
      patch 'hide' => 'users#hide'
      put "/users/:id/hide" => "users#hide", as: 'users_hide'
    end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include JpPrefecture
  jp_prefecture :prefecture_code

  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :post_commnets
  has_many :posts, dependent: :destroy

  attachment :profile_image, destroy: false
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true, allow_blank: true
  validates :email, presence: true, allow_blank: true
  validates :password, presence: true, length: {minimum:6}, on: :create, allow_blank: true
  validates :introduction, presence: true, length: { maximum: 50 }, on: :update, allow_blank: true
  validates :postal_code, presence: true, on: :create, allow_blank: true
  validates :prefecture_code, presence: true, on: :create, allow_blank: true
  validates :city, presence: true, on: :create, allow_blank: true

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.search_for(content, method)
      # methodがperfectだったら
    if method == 'perfect'
      # データベースから条件に一致したものを一件or複数とってくる
      User.where(name: content)
      # perfctじゃなかったらforword（前方一致）に移動する
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
      # perfctじゃなかったらforword（後方一致）に移動する
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      # 全く一致しない場合
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  # いいね機能
  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  # 住所検索機能
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # 検索機能
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  before_action :reject_user, only: [:create]
  # ゲストログイン機能
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end


  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  private
  def sign_up_params
    params.permit(:name, :password)
  end

  def account_update_params
    params.permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit, :update]

  def index
    @users = User.where(is_deleted: false)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(6).order(created_at: :desc)
    @post = Post.new
    # ユーザーがいいねしている投稿一覧が欲しい
    @favorited_posts = @user.favorited_posts
  end

  def edit
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),notice:"アップデートに成功しました。"
    else
      render "edit"
    end
  end

  def confirm
    @user = User.find(params[:id])
  end

  def hide
    @user = User.find(params[:id])
    if @user.email =='guest@example.com'
      # for guest_user
      flash[:notice] = "ゲストは退会できません。"
      redirect_to confirm_user_path
    else
       #is_deletedカラムにフラグを立てる(defaultはfalse)
      @user.update!("is_deleted"=>"#{params[:is_deleted]}")
      #ログアウトさせる
      reset_session
      redirect_to root_path
    end
  end

  def zipedit
  params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!--フォロー機能-->
 <% if current_user != user %>
   <% if current_user.followings?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-success" %>
   <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST , class: "btn btn-primary"%>
   <% end %>
 <% end %>

app/views/users/_index.html.erb
<!--<table class='table'>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>image</th>-->
<!--      <th>name</th>-->
<!--      <th colspan="3"></th>-->
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>ユーザー名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to user_path(user) do %>
          <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, size: "50x50", fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td></td>
        <th><%= user.name %></th>
        <th></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.posts.html.erb
  <div class='container'>
    <div class='row'>
      <div class="card-columns">
        <% @posts.each do |post| %>
          <div class="card mx-auto mt-4 shadow-lg">
            <%= link_to post_path(post.id) do %>
              <%= attachment_image_tag post, :image, class:"card-img-top"; %>
            <% end %>
            <div class="card-body">
              <div class="row">
                <div class="col-10">
                  <p class="card-title">
                    <%= link_to(post_path(post.id), class:"text-dark") do %>
                      タイトル：<%= post.title.truncate(5) %>
                    <% end %>
                  </p>
                  <p class="post-text">内容：<%= post.caption.truncate(5) %></p>
                  <p><%= link_to "コメント#{post.post_comments.count} 件", post_path(post.id), class:"text-dark" %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/confirm.html.erb
<% if user_signed_in? && @user.id == current_user.id %>
  <div class="container">
    <div class="row">
      <div class="mx-auto text-center">
        <h4 class="mt-5">本当に退会しますか？</h4>
        <p class="mt-3">退会すると、会員登録情報や</br>
        これまでの投稿閲覧できなくなります。</br>
        退会する場合は、「退会する」をクリックしてください。</p>
        <div class="col-10 mt-2 mx-auto">
          <%= link_to "退会しない", user_path(@user.id), class:"btn btn-info btn-sm mr-5" %>
          <%= link_to "退会する", hide_user_path(id: @user.id, is_deleted: true), method: :patch, class:"btn btn-sm btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>プロフィール編集</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :profile_image, "プロフィール画像" %>
        <%= f.attachment_field :profile_image, class: "form-control-file profile_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, "紹介文" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    <%= link_to "退会画面へ", confirm_user_path %>
  </div>
</div>

app/views/users/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>ユーザー画像</th>
      <th>名前</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, size: "50x50", fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.followings?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to '投稿を見る', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
  <div class='container show'>
    <div class='row'>
      <div class='col-md-3'>
      <% if current_user == @user %>
        <h2>マイページ</h2>
      <% else %>
        <h2>ユーザー情報</h2>
      <% end %>
        <table class='table'>
          <tr><%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "no_image.jpg", size: "200x200", class:"mt-3 rounded-circle"; %>
          </tr>
          <tr>
            <th>名前：<%= @user.name %> </th>
          </tr>
          <tr>
            <th>フォロー：<%= link_to @user.followings.count, user_followings_path(@user) %>人</th>
          </tr>
          <tr>
            <th>フォロワー：<%= link_to @user.followers.count, user_followers_path(@user) %>人</th>
          </tr>
          <tr>
            <th>紹介文：<br>　<%= @user.introduction %></th>
          </tr>
        </table>
        <% if current_user == @user %>
            <%= link_to "マイページを編集する", edit_user_path(@user) %>
          </div>
          <%= render "/users/follow", user:@user %>

          <div class='col-md-8 offset-md-1'>
            <h1><%= @user.name %>さんの投稿</h1>
              <%= render "/users/user.posts/", user: @user%>
              <div class="pagenation">
                <%= paginate @posts %>
              </div>
          </div>
        <% else%>
            <%= render "/users/follow", user:@user %>
          </div>

          <div class='col-md-8 offset-md-1'>
            <h2><%= @user.name %>さんの投稿</h2>
              <%= render "/users/user.posts/", user: @user %>
            <div class="pagenation">
              <%= paginate @posts %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>