config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'registrations/sign_up_params'
  devise_for :users
  root :to => "homes#top"
  get "/about" => "homes#about"

  # ゲストログイン機能
  get '/homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search/search'
  get '/search', to: 'searches#search'

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get 'confirm' => 'users#confirm'
      patch 'hide' => 'users#hide'
      put "/users/:id/hide" => "users#hide", as: 'users_hide'
    end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <h4 class="title-logo font-weight-bold">いろ<span class="title-logo-2 font-weight-bold">どり</span></h4>
    <div class="">
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <p class="p-3 text-info">ようこそ、<%= current_user.name %>さん</p>
            <li class="nav-item">
              <%= link_to "みんなの投稿", posts_path, class: "fas fa-camera nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user.id), class: "fas fa-user nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿する", new_post_path, class: "far fa-plus-square nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", users_path, class: "fas fa-users nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path,  method: :delete, class: "fas fa-sign-out-alt nav-link text-teal m-3" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ホーム", root_path, class: "fas fa-home nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "サイト詳細", about_path, class: "fas fa-link nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-teal m-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "fas fa-user-plus nav-link text-teal m-3", data: {"turbolinks" => false} %>
            </li>
            <li class="nav-item">
              <%= link_to "簡単ログイン", homes_guest_sign_in_path, class: "far fa-user nav-link text-teal m-3" %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Irodori</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
      <header>
        <%= render 'layouts/header' %>
      </header>
      <%= yield %>
    </body>
  </html>